In [1]:
import numpy as np


In [2]:
array_reloaded=np.load('sidak.npy') 
print(array_reloaded) 

[[ 90  99 102 ...  23  59  84]
 [ 61  73  77 ...  27  56  77]
 [ 48  58  59 ...  22  56  82]
 ...
 [168 177 174 ...  36  21  14]
 [143 154 152 ...  71 107 129]
 [ 72  79  78 ...  25  38  36]]


In [3]:
np.load('sidak.npy')

array([[ 90,  99, 102, ...,  23,  59,  84],
       [ 61,  73,  77, ...,  27,  56,  77],
       [ 48,  58,  59, ...,  22,  56,  82],
       ...,
       [168, 177, 174, ...,  36,  21,  14],
       [143, 154, 152, ...,  71, 107, 129],
       [ 72,  79,  78, ...,  25,  38,  36]], dtype=uint8)